//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : DrivieTalkie
//  @ File Name : GtalkConnection.java
//  @ Date : 07/04/2013
//  @ Author : 
//
//




public class GtalkConnection extends XmppServerConnection {
	public void GtalkConnection() {
	
	}
}
